## THIS IS A PRODUCTION DOCKERFILE ##

FROM node
WORKDIR /usr/src/app
COPY package*.json .
#RUN node --version
RUN npm install
COPY . .
RUN npx prisma migrate deploy
RUN npx prisma generate
RUN npx prisma db seed -- --environment prod
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]

## THIS IS A PRODUCTION DOCKERFILE ##
